spring:
  datasource:
#    url: jdbc:h2:file:./h2/intergrationtestdb
    url: jdbc:h2:file:./h2/testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  flyway:
    locations: classpath:db/migration
server:
  #端口号
  port: 8083